# fly.toml app configuration file generated for typingmind-mcp-pah50q on 2025-06-06T08:56:51Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'typingmind-mcp-pah50q'
primary_region = 'ord'

[build]

[http_service]
  internal_port = 50880
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
